# Generated by Django 6.0.5 on 2026-09-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_cell_options_alter_examination_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cell",
            name="main_datapoint",
        ),
        migrations.RemoveConstraint(
            model_name="cell",
            name="unique_column_and_examination",
        ),
        migrations.RemoveConstraint(
            model_name="column",
            name="unique_dataset_column",
        ),
        migrations.RemoveField(
            model_name="historicalcolumn",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="historicalcolumn",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="column",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="examination",
        ),
        migrations.RemoveField(
            model_name="column",
            name="dataset",
        ),
        migrations.DeleteModel(
            name="HistoricalCell",
        ),
        migrations.DeleteModel(
            name="HistoricalColumn",
        ),
        migrations.DeleteModel(
            name="Cell",
        ),
        migrations.DeleteModel(
            name="Column",
        ),
    ]
