# Generated by Django 5.1.6 on 2025-02-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_squashed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="lives_with",
            new_name="parental_presence",
        ),
        migrations.RenameField(
            model_name="historicaladdress",
            old_name="lives_with",
            new_name="parental_presence",
        ),
    ]
