# Generated by Django 5.1.6 on 2025-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_historicalproband_cpr_alter_proband_cpr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrelative",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("second_father", "Second father"),
                    ("non_bio_father", "Non-biological father"),
                    ("stepfather", "Stepfather"),
                    ("mother", "Mother"),
                    ("second_mother", "Second mother"),
                    ("non_bio_mother", "Non-biological mother"),
                    ("stepmother", "Stepmother"),
                    ("sibling", "Sibling"),
                    ("same_father", "Half-sibling, same father"),
                    ("same_mother", "Half-sibling, same mother"),
                    ("non_bio_sibling", "Non-biological sibling"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="relative",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("second_father", "Second father"),
                    ("non_bio_father", "Non-biological father"),
                    ("stepfather", "Stepfather"),
                    ("mother", "Mother"),
                    ("second_mother", "Second mother"),
                    ("non_bio_mother", "Non-biological mother"),
                    ("stepmother", "Stepmother"),
                    ("sibling", "Sibling"),
                    ("same_father", "Half-sibling, same father"),
                    ("same_mother", "Half-sibling, same mother"),
                    ("non_bio_sibling", "Non-biological sibling"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=15,
            ),
        ),
    ]
