# Generated by Django 5.1.7 on 2025-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_historicalrelative_relation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalinstitution",
            name="type",
            field=models.CharField(
                choices=[
                    ("nursery", "Nursery"),
                    ("daycare", "Daycare"),
                    ("kindergarten", "Kindergarten"),
                    ("forest_kindergarten", "Forest kindergarten"),
                    ("school", "School"),
                    ("after_school_care", "After school care"),
                    ("private", "Private"),
                    ("boarding_school", "Boarding school"),
                    ("workplace", "Workplace"),
                    ("club", "Club"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaleducationalinstitution",
            name="type",
            field=models.CharField(
                choices=[
                    ("nursery", "Nursery"),
                    ("daycare", "Daycare"),
                    ("kindergarten", "Kindergarten"),
                    ("forest_kindergarten", "Forest kindergarten"),
                    ("school", "School"),
                    ("after_school_care", "After school care"),
                    ("private", "Private"),
                    ("boarding_school", "Boarding school"),
                    ("workplace", "Workplace"),
                    ("club", "Club"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
    ]
