# Generated by Django 5.1.7 on 2025-08-01 09:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_educationalinstitution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalInstitutionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_year", models.IntegerField(blank=True, null=True)),
                ("room_size", models.IntegerField(blank=True, null=True)),
                ("number_children", models.IntegerField(blank=True, null=True)),
                ("time_spent", models.IntegerField(blank=True, null=True)),
                ("smoking", models.BooleanField(blank=True, null=True)),
                ("number_smokers", models.IntegerField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="base.educationalinstitution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalEducationalInstitutionStats",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("build_year", models.IntegerField(blank=True, null=True)),
                ("room_size", models.IntegerField(blank=True, null=True)),
                ("number_children", models.IntegerField(blank=True, null=True)),
                ("time_spent", models.IntegerField(blank=True, null=True)),
                ("smoking", models.BooleanField(blank=True, null=True)),
                ("number_smokers", models.IntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.educationalinstitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical education institution stats",
                "verbose_name_plural": "historical education institution statss",
                "db_table": "zz_base_institution_stats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
