# Generated by Django 5.1.7 on 2025-08-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_educationinstitutionstats_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationalinstitutionstats",
            options={"verbose_name_plural": "Educational Institution Stats"},
        ),
        migrations.AlterModelOptions(
            name="historicaleducationalinstitutionstats",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical educational institution stats",
                "verbose_name_plural": "historical Educational Institution Stats",
            },
        ),
    ]
