# Generated by Django 5.2.5 on 2025-09-22 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_educationalinstitutionstats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="build_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year of construction",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="email_proband",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="size",
            field=models.IntegerField(
                blank=True,
                help_text="Size in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="applied_date",
            field=models.DateField(
                blank=True,
                help_text="Date from when consent was applied",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="withdrawn_date",
            field=models.DateField(
                blank=True,
                help_text="Date from when consent was withdrawn (if at all)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="build_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year of construction",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="email_proband",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="size",
            field=models.IntegerField(
                blank=True,
                help_text="Size in square meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsent",
            name="applied_date",
            field=models.DateField(
                blank=True,
                help_text="Date from when consent was applied",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsent",
            name="withdrawn_date",
            field=models.DateField(
                blank=True,
                help_text="Date from when consent was withdrawn (if at all)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="Date consent was given",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalconsent",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="Date consent was given",
                null=True,
            ),
        ),
    ]
