# Generated by Django 5.2.5 on 2025-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_address_build_year_address_email_proband_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproband",
            name="proband_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="proband",
            name="proband_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
