# Generated by Django 5.2.5 on 2025-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_historicalproband_proband_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consenttype",
            name="name",
            field=models.CharField(max_length=61),
        ),
        migrations.AlterField(
            model_name="historicalconsenttype",
            name="name",
            field=models.CharField(max_length=61),
        ),
    ]
