# Generated by Django 5.2.8 on 2025-11-28 09:49

from django.db import migrations


def pad_cpr_numbers(apps, schema_editor):
    """
    Pad CPR numbers with leading zeros to ensure they are exactly 10 characters long.
    This applies to both current Proband records and historical records.
    """
    Proband = apps.get_model("base", "Proband")
    HistoricalProband = apps.get_model("base", "HistoricalProband")

    # Update current Proband records
    probands_to_update = []
    for proband in Proband.objects.all():
        if proband.cpr and len(proband.cpr) < 10:
            proband.cpr = proband.cpr.zfill(10)
            probands_to_update.append(proband)

    if probands_to_update:
        Proband.objects.bulk_update(probands_to_update, ["cpr"])

    # Update historical records
    historical_records_to_update = []
    for historical_proband in HistoricalProband.objects.all():
        if historical_proband.cpr and len(historical_proband.cpr) < 10:
            historical_proband.cpr = historical_proband.cpr.zfill(10)
            historical_records_to_update.append(historical_proband)

    if historical_records_to_update:
        HistoricalProband.objects.bulk_update(historical_records_to_update, ["cpr"])


def reverse_pad_cpr_numbers(apps, schema_editor):
    """
    Reverse migration - note that we cannot reliably restore the original CPR format
    as we don't know which CPRs originally had leading zeros vs. which were padded.
    This reverse operation is a no-op to prevent data loss.
    """
    # No-op: We cannot reliably reverse this operation without knowing
    # which CPRs originally had leading zeros
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_consenttype_name_and_more"),
    ]

    operations = [
        migrations.RunPython(pad_cpr_numbers, reverse_pad_cpr_numbers),
    ]
