# Generated by Django 5.2.9 on 2026-03-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_rename_fk_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalconsent",
            name="fk_consent_type",
        ),
        migrations.RemoveField(
            model_name="historicalconsent",
            name="fk_proband",
        ),
        migrations.RemoveField(
            model_name="historicalnote",
            name="fk_proband",
        ),
        migrations.RemoveField(
            model_name="historicalrelative",
            name="fk_proband",
        ),
        migrations.AddField(
            model_name="historicalconsent",
            name="consent_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.consenttype",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsent",
            name="proband",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.proband",
            ),
        ),
        migrations.AddField(
            model_name="historicalnote",
            name="proband",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.proband",
            ),
        ),
        migrations.AddField(
            model_name="historicalrelative",
            name="proband",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="base.proband",
            ),
        ),
    ]
