# Generated by Django 4.2.11 on 2024-03-25 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATCCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ICDCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "ordination_comment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("initiated_by_parents", "Initiated by parents"),
                            (
                                "initiated_by_external_physician",
                                "Initiated by physicians outside COPSAC",
                            ),
                            (
                                "continued_past_ordination_by_parents",
                                "Continued past ordination by parents",
                            ),
                            (
                                "prematurely_stopped_by_parents",
                                "Prematurely stopped by parents",
                            ),
                            (
                                "prematurely_stopped_due_to_changes_in_algorithm",
                                "Prematurely stopped due to changes in algorithm. Needs to pause.",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("pn", models.BooleanField(default=False)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("prn", "Pro re nata"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("nasal", "Nasal"),
                            ("vaginal", "Vaginal"),
                            ("oral", "Oral"),
                            ("cutaneous", "Cutaneous"),
                            ("oromucusal", "Oromucusal"),
                            ("intravenous", "Intravenous"),
                            ("inhaled", "Inhaled"),
                            ("ocular", "Ocular"),
                            ("intramuscular", "Intramuscular"),
                            ("auricular", "Auricular"),
                            ("rectal", "Rectal"),
                            ("subcutaneous", "Subcutaneous"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "route_spec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("pmdi", "pMDI"),
                            ("nebulized", "Nebulized"),
                            ("turbohaler", "Turbohaler"),
                            ("easyhaler", "Easyhaler"),
                            ("autohaler", "Autohaler"),
                        ],
                        max_length=255,
                    ),
                ),
                ("source_type", models.BooleanField(default=False)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("g", "g"),
                            ("mg", "mg"),
                            ("mcg", "mcg"),
                            ("ml", "ml"),
                            ("U", "U"),
                        ],
                        max_length=255,
                    ),
                ),
                ("dose", models.CharField(blank=True, null=True, max_length=255)),
                ("comments", models.CharField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "lock_status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked", "Locked"),
                            ("validated", "Validated"),
                        ],
                        default="unlocked",
                        max_length=9,
                    ),
                ),
                (
                    "atc_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare_records.atccode",
                    ),
                ),
                (
                    "proband",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.proband",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMedication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "ordination_comment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("initiated_by_parents", "Initiated by parents"),
                            (
                                "initiated_by_external_physician",
                                "Initiated by physicians outside COPSAC",
                            ),
                            (
                                "continued_past_ordination_by_parents",
                                "Continued past ordination by parents",
                            ),
                            (
                                "prematurely_stopped_by_parents",
                                "Prematurely stopped by parents",
                            ),
                            (
                                "prematurely_stopped_due_to_changes_in_algorithm",
                                "Prematurely stopped due to changes in algorithm. Needs to pause.",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("pn", models.BooleanField(default=False)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("prn", "Pro re nata"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("nasal", "Nasal"),
                            ("vaginal", "Vaginal"),
                            ("oral", "Oral"),
                            ("cutaneous", "Cutaneous"),
                            ("oromucusal", "Oromucusal"),
                            ("intravenous", "Intravenous"),
                            ("inhaled", "Inhaled"),
                            ("ocular", "Ocular"),
                            ("intramuscular", "Intramuscular"),
                            ("auricular", "Auricular"),
                            ("rectal", "Rectal"),
                            ("subcutaneous", "Subcutaneous"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "route_spec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("pmdi", "pMDI"),
                            ("nebulized", "Nebulized"),
                            ("turbohaler", "Turbohaler"),
                            ("easyhaler", "Easyhaler"),
                            ("autohaler", "Autohaler"),
                        ],
                        max_length=255,
                    ),
                ),
                ("source_type", models.BooleanField(default=False)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("g", "g"),
                            ("mg", "mg"),
                            ("mcg", "mcg"),
                            ("ml", "ml"),
                            ("U", "U"),
                        ],
                        max_length=255,
                    ),
                ),
                ("dose", models.CharField(blank=True, null=True, max_length=255)),
                ("comments", models.CharField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "lock_status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked", "Locked"),
                            ("validated", "Validated"),
                        ],
                        default="unlocked",
                        max_length=9,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atc_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="healthcare_records.atccode",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proband",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.proband",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical medication",
                "verbose_name_plural": "historical medications",
                "db_table": "zz_healthcare_records_medication",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalICDCode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("description", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical icd code",
                "verbose_name_plural": "historical icd codes",
                "db_table": "zz_healthcare_records_icdcode",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_chronic", models.BooleanField(default=False)),
                (
                    "medical_attention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_attended", "Not attended"),
                            ("private_physician", "Private physician"),
                            ("emergency_doctor", "Emergency doctor"),
                            ("casualty_department", "Casualty department"),
                            ("pedriatric_admission_ward", "Pedriatric admission ward"),
                            ("hospitalized", "Hospitalized"),
                            ("abc_clinic", "ABC Clinic"),
                            ("day_clinic", "Day clinic"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("adverse_event", models.BooleanField(default=False)),
                (
                    "intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("serious", "Serious"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("no_action", "No action"),
                            ("dose_changed", "Dose changed"),
                            ("temporarily_stopped", "Temporarily stopped"),
                            ("stopped", "Stopped"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_dvitamin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_h1n1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_antibiotics",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "lock_status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked", "Locked"),
                            ("validated", "Validated"),
                        ],
                        default="unlocked",
                        max_length=9,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="healthcare_records.icdcode",
                    ),
                ),
                (
                    "proband",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.proband",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical diagnosis",
                "verbose_name_plural": "historical diagnosiss",
                "db_table": "zz_healthcare_records_diagnosis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalATCCode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical atc code",
                "verbose_name_plural": "historical atc codes",
                "db_table": "zz_healthcare_records_atccode",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_chronic", models.BooleanField(default=False)),
                (
                    "medical_attention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_attended", "Not attended"),
                            ("private_physician", "Private physician"),
                            ("emergency_doctor", "Emergency doctor"),
                            ("casualty_department", "Casualty department"),
                            ("pedriatric_admission_ward", "Pedriatric admission ward"),
                            ("hospitalized", "Hospitalized"),
                            ("abc_clinic", "ABC Clinic"),
                            ("day_clinic", "Day clinic"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("adverse_event", models.BooleanField(default=False)),
                (
                    "intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("serious", "Serious"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("no_action", "No action"),
                            ("dose_changed", "Dose changed"),
                            ("temporarily_stopped", "Temporarily stopped"),
                            ("stopped", "Stopped"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_dvitamin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_h1n1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "causality_antibiotics",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("not_applicable", "Not applicable"),
                            ("probably", "Probably"),
                            ("possibly", "Possibly"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=255,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "lock_status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked", "Locked"),
                            ("validated", "Validated"),
                        ],
                        default="unlocked",
                        max_length=9,
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare_records.icdcode",
                    ),
                ),
                (
                    "proband",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.proband",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="atccode",
            options={"verbose_name": "ATC Code", "verbose_name_plural": "ATC Codes"},
        ),
        migrations.AlterModelOptions(
            name="diagnosis",
            options={"verbose_name_plural": "Diagnoses"},
        ),
        migrations.AlterModelOptions(
            name="historicalatccode",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ATC Code",
                "verbose_name_plural": "historical ATC Codes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldiagnosis",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical diagnosis",
                "verbose_name_plural": "historical Diagnoses",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalicdcode",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ICD Code",
                "verbose_name_plural": "historical ICD Codes",
            },
        ),
        migrations.AlterModelOptions(
            name="icdcode",
            options={"verbose_name": "ICD Code", "verbose_name_plural": "ICD Codes"},
        ),
    ]
