# Generated by Django 5.1.6 on 2025-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_records", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Proband's mother")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnosis",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Proband's mother")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="historicalmedication",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Proband's Mother")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Proband's Mother")],
                default="proband",
                max_length=7,
            ),
        ),
    ]
