# Generated by Django 5.1.6 on 2025-02-17 14:39

from django.db import migrations


def translate_recipient(apps, schema_editor):
    Medication = apps.get_model("healthcare_records", "Medication")
    Medication.objects.filter(source_type=True).update(recipient="mother")


def untranslate_recipient(apps, schema_editor):
    Medication = apps.get_model("healthcare_records", "Medication")
    Medication.objects.filter(recipient="mother").update(source_type=True)


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthcare_records",
            "0002_diagnosis_recipient_historicaldiagnosis_recipient_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(translate_recipient, untranslate_recipient),
    ]
