# Generated by Django 5.1.6 on 2025-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_records", "0003_translate_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmedication",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="source_type",
        ),
    ]
