# Generated by Django 5.1.6 on 2025-07-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_records", "0006_alter_historicalmedication_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Mother of proband")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosis",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Mother of proband")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmedication",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Mother of proband")],
                default="proband",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="recipient",
            field=models.CharField(
                choices=[("proband", "Proband"), ("mother", "Mother of proband")],
                default="proband",
                max_length=7,
            ),
        ),
    ]
