# Generated by Django 5.1.7 on 2025-07-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_records", "0007_alter_diagnosis_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmedication",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("mcg", "mcg"),
                    ("ml", "ml"),
                    ("U", "U"),
                    ("mcmol", "mcmol"),
                    ("dr", "drops"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("g", "g"),
                    ("mg", "mg"),
                    ("mcg", "mcg"),
                    ("ml", "ml"),
                    ("U", "U"),
                    ("mcmol", "mcmol"),
                    ("dr", "drops"),
                ],
                max_length=255,
            ),
        ),
    ]
